---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-client
  labels:
     app: my-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-client
  template:
    metadata:
      labels:
        app: my-client
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret-client
      containers:
      - name: my-client
        image: registry.gitlab.com/uthayasurian98/my-client
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SERVER_ADDRESS
          value: my-server
        - name: SERVER_PORT
          value: "30152"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 30152
        imagePullPolicy: Always
