---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server
  labels:
     app: my-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-server
  template:
    metadata:
      labels:
        app: my-server
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: my-server
        image: registry.gitlab.com/uthayasurian98/server-deployment
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LISTEN_PORT
          value: "30152"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 30152
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: my-server
spec:
  selector:
    app: my-server
  ports:
  - name: my-server
    port: 30152
    protocol: TCP
  type: ClusterIP

